name: Build Custom Shipping Docker Image

on:
  push:
    branches: [ main ]
    paths:
      - 'src/shipping/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'src/shipping/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}
      
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      
    - name: Extract version
      id: version
      run: |
        if [[ $GITHUB_REF == refs/tags/* ]]; then
          VERSION=${GITHUB_REF#refs/tags/}
        else
          VERSION=dev-$(date +%Y%m%d)-${GITHUB_SHA::8}
        fi
        echo "version=$VERSION" >> $GITHUB_OUTPUT
      
    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./src/shipping/Dockerfile
        platforms: linux/amd64,linux/arm64
        push: true
        tags: |
          ghcr.io/${{ github.repository_owner }}/opentelemetry-demo-shipping:latest
          ghcr.io/${{ github.repository_owner }}/opentelemetry-demo-shipping:${{ steps.version.outputs.version }}
          ghcr.io/${{ github.repository_owner }}/opentelemetry-demo-shipping:${{ github.sha }}
        cache-from: type=gha
        cache-to: type=gha,mode=max