name: Build Quote CF Docker Image

on:
  push:
    branches: [ main ]
    paths:
      - 'src/quote-cf/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'src/quote-cf/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      
    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: ./src/quote-cf
        file: ./src/quote-cf/Dockerfile
        push: true
        tags: |
          ghcr.io/${{ github.repository_owner }}/opentelemetry-demo-quote-cf:latest
          ghcr.io/${{ github.repository_owner }}/opentelemetry-demo-quote-cf:${{ github.sha }}
        cache-from: type=gha
        cache-to: type=gha,mode=max