name: Build Quote CF Docker Image

on:
  push:
    branches: [ main ]
    paths:
      - 'src/quote-cf/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'src/quote-cf/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      
    - name: Build Docker image
      uses: docker/build-push-action@v5
      with:
        context: ./src/quote-cf
        file: ./src/quote-cf/Dockerfile
        push: false
        tags: |
          quote-cf:latest
          quote-cf:${{ github.sha }}
        cache-from: type=gha
        cache-to: type=gha,mode=max